### ISSUE TITLE
Remove more-itertools dependency 

### ISSUE THREAD

**Issue by Florents-Tselai** [Florents-Tselai/WarcDB#21]
We use only one function which we should probably copy paste.

**Comment by edsu** [comment]
There's no harm in bringing it in for one function in my opinion.

**Comment by Florents-Tselai** [comment]
I believe we've too many dependencies for something relatively straightforward, and sooner or later, people will start being blocked by version paths that pip won't be able to resolve.

In an ideal world, the whole thing could be done with standard Python lib (since sqlite3 is standard Python)

**Comment by edsu** [comment]
I don't think this is a problem, unless we get stuck on some old versions of things.
