### ISSUE TITLE
Extract common HTTP response headers

### ISSUE THREAD

**Issue by edsu** [Florents-Tselai/WarcDB#22]
It's great that we have the original HTTP Headers for responses stored in the `response.http_headers` column. But I think it would be helpful to extract and normalize some common ones, to help people easily query them without needing to parse and manipulate JSON:

- Content-Type (http_content_type)
- Content-Length (http_content_length)
- Server (http_server)
- Date (http_date)
- Status (http_status) (this isn't actually header, but should be easily extractable)

**Comment by edsu** [comment]
On second thought maybe we could have specific views that did this? Is this feasible?

I do think that http status code would need to be added to the http_headers JSON though? Or maybe as a separate column?

**Comment by Florents-Tselai** [comment]
Unless we run into a blocker (i.e., we don’t capture data appropriately or lose something) I suggest we don’t alter any tables and instead start by adding some views, but this is where documentation and keeping track of what is available becomes essential.

Do you know if there is any bibliography or previous research here? What are some standard questions / reports we could start adding ?

**Comment by edsu** [comment]
I agree, views would be great. Maybe we could start with a simple one for reporting response content-types in the database?

**Comment by edsu** [comment]
I'm going to close this since we are going with the view approach. I will open a separate ticket for HTTP status code since that is not currently modeled in the database.
